Update upstream_sync.yml

diff --git a/.github/workflows/upstream_sync.yml b/.github/workflows/upstream_sync.yml
--- a/.github/workflows/upstream_sync.yml
+++ b/.github/workflows/upstream_sync.yml
@@ -59,7 +59,7 @@ jobs:
 
     # Step 4: Check sync result
     - name: Sync check
-        if: failure()
-        run: |
-          echo "[Error] 由于上游仓库的 workflow 文件变更，导致 GitHub 自动暂停了本次自动更新，你需要手动 Sync Fork 一次。
-          exit 1
+      if: failure()
+      run: |
+        echo "[Error] 由于上游仓库的 workflow 文件变更，导致 GitHub 自动暂停了本次自动更新，你需要手动 Sync Fork 一次。
+        exit 1
